# Site Settings
baseurl: ""

# Features Setting
# Turn subpages on or off
publications: True
presentations: True
blog: True

# Language of the website
lang: en

# Search engine optimization settings
title: Tu Hoang
tagline: A jekyll theme for academic portfolios
description: The personal website of Tu Hoang. Privacy and Security Researcher in various topics (Decentralized Systems, Blockchain, Differential Privacy, Machine Learning/Deep Learnling).
author: Tu Hoang (tuhoang)
# twitter:
#   username: chrjabs
#   card: A jekyll theme for academic portfolios
logo: /assets/img/smile.png
social:
  name: Tu Hoang
  links:
    - www.tuhoang.me
locale: en_IT

# Page Settings
theme_settings:
  title: Tu Hoang Personal Website

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Hoang
  first_name: [Anh-Tu]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
